#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit 1
fi

# Get AUR helper from args
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <yay|pamac>"
    exit 1
fi

choice=$1

mkdir -p /tmp/schildmann/aur
cd /tmp/schildmann/aur

if [ "$choice" == "yay" ]; then
    install_yay
elif [ "$choice" == "pamac" ]; then
    install_pamac
else
    echo "Invalid choice"
    exit 1
fi

cd ..
rm -rf /tmp/schildmann/aur

install_yay() {
    sudo pacman -S git base-devel --noconfirm
    wget -O aur_install https://arch.schildman.net/aur_install
    chmod +x aur_install
    ./aur_install yay
}

install_pamac() {
    sudo pacman -S git base-devel --noconfirm
    sudo pacman -S libhandy libadwaita --noconfirm
    wget -O aur_install https://arch.schildman.net/aur_install
    chmod +x aur_install
    ./aur_install libpamac-aur pamac-aur
}