#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit
fi

mkdir -p /tmp/schildmann/base
cd /tmp/schildmann/base
wget -O aur_install https://arch.schildmann.net/aur_install
chmod +x aur_install
export SCHILDMANN=1
sudo pacman -Syu --noconfirm --needed firefox neovim less vlc gimp inkscape libreoffice-fresh rustup code alacritty yubioath-desktop btop kdiff3 krename zip arj unarj p7zip unrar
./aur_install thorium-browser-bin spotify teamviewer octopi ttf-ms-fonts jetbrains-toolbox zplug vimv
sudo pacman -Rcns --noconfigm konsole okular haruna
cd ..
rm -rf /tmp/schildmann/base
