#!/usr/bin/bash
set -e

# Install required packages
sudo pacman -S qemu libvirt dmidecode edk2-ovmf virt-manager dnsmasq iptables-nft tree --noconfirm
sudo systemctl enable libvirtd

# Create dir structure for Win11
sudo mkdir -p /etc/libvirt/hooks/qemu.d/win11/prepare/begin
sudo mkdir -p /etc/libvirt/hooks/qemu.d/win11/release/end

# Create hook scripts
sudo wget 'https://raw.githubusercontent.com/PassthroughPOST/VFIO-Tools/master/libvirt_hooks/qemu' -O /etc/libvirt/hooks/qemu
sudo chmod +x /etc/libvirt/hooks/qemu

# Create start script
cat <<EOF | sudo tee /etc/libvirt/hooks/qemu.d/win11/prepare/begin/start.sh
#!/bin/bash
## Helpful to read output when debugging
set -x

# Stop display manager
systemctl stop display-manager.service
## Uncomment the following line if you use GDM
#killall gdm-x-session

# Unbind VTconsoles
echo 0 > /sys/class/vtconsole/vtcon0/bind
echo 0 > /sys/class/vtconsole/vtcon1/bind

# Unbind EFI-Framebuffer
echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind

# Avoid a Race condition by waiting 2 seconds. This can be calibrated to be shorter or longer if required for your system
sleep 2

# Unload all Nvidia drivers
modprobe -r nvidia_drm
modprobe -r nvidia_modeset
modprobe -r nvidia_uvm
modprobe -r nvidia

## Load vfio
modprobe vfio
modprobe vfio_iommu_type1
modprobe vfio_pci
EOF
sudo chmod +x /etc/libvirt/hooks/qemu.d/win11/prepare/begin/start.sh

# Create end script
cat <<EOF | sudo tee /etc/libvirt/hooks/qemu.d/win11/release/end/stop.sh
#!/bin/bash
set -x

## Unload vfio
modprobe -r vfio_pci
modprobe -r vfio_iommu_type1
modprobe -r vfio

# Rebind VT consoles
echo 1 > /sys/class/vtconsole/vtcon0/bind
echo 1 > /sys/class/vtconsole/vtcon1/bind

nvidia-xconfig --query-gpu-info > /dev/null 2>&1
echo "efi-framebuffer.0" > /sys/bus/platform/drivers/efi-framebuffer/bind

modprobe nvidia_drm
modprobe nvidia_modeset

modprobe nvidia_uvm
modprobe nvidia

# Restart Display Manager
systemctl start display-manager.service
EOF
sudo chmod +x /etc/libvirt/hooks/qemu.d/win11/release/end/stop.sh

# List structure
tree /etc/libvirt/hooks