#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit
fi

# Install deps if not installed
sudo pacman -S git base-devel libhandy libadwaita --noconfirm

# Download repo from AUR
git clone https://aur.archlinux.org/libpamac-aur.git
git clone https://aur.archlinux.org/pamac-aur.git

# Install
cd libpamac-aur
makepkg -si --noconfirm
cd ../pamac-aur
makepkg -si --noconfirm

# Remove directories
cd ..
rm -rf libpamac-aur
rm -rf pamac-aur
