#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit 1
fi

mkdir -p /tmp/schildmann/aur
cd /tmp/schildmann/aur

sudo pacman -S git base-devel --noconfirm
sudo pacman -S libhandy libadwaita --noconfirm
wget -O aur_install https://arch.schildmann.net/aur_install
chmod +x aur_install
export SCHILDMANN=1
./aur_install libpamac-aur pamac-aur

cd ..
rm -rf /tmp/schildmann/aur