#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit
fi

mkdir -p /tmp/schildmann/teamviewer
cd /tmp/schildmann/teamviewer
wget -O aur_install https://arch.schildmann.net/aur_install
chmod +x aur_install
export SCHILDMANN=1
./aur_install teamviewer
cd ..
rm -rf /tmp/schildmann/teamviewer