#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit
fi

VIRT_USER=$USER

sudo pacman -Syu --noconfirm --needed qemu libvirt dmidecode edk2-ovmf virt-manager dnsmasq iptables-nft
sudo systemctl enable libvirtd
sudo usermod -aG libvirt $VIRT_USER
