#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit 1
fi

sudo pacman -Syu --noconfirm --needed git base-devel

mkdir -p /tmp/schildmann/aur
cd /tmp/schildmann/aur

wget -O aur_install https://arch.schildmann.net/aur_install
chmod +x aur_install
export SCHILDMANN=1
./aur_install yay

cd ..
rm -rf /tmp/schildmann/aur