#!/usr/bin/bash
set -e

# Check if user is root and abort
if [ "$EUID" -eq 0 ]; then
    echo "Do not run as root"
    exit
fi

# Install git if not installed
sudo pacman -S git base-devel --noconfirm

# Download yay repo from AUR
git clone https://aur.archlinux.org/yay.git

# Change directory to yay
cd yay

# Build and install yay
makepkg -si --noconfirm

# Remove yay directory
cd ..
rm -rf yay
